try:
    raise ValueError("fail")
except ValueError as e:
    print(e.message)
finally:
    print("oof")